### ISSUE TITLE
Token renewal fails

### ISSUE THREAD

**Issue by mariusflorescu** [authts/react-oidc-context#294]
hi there,

so using the `singinRedirect` method works, both authorize redirect and code request work as expected.

However, when the automatic renewal should take place, something weird happens. The code request is being made to `https://localhost:3000/?code=...`

![both requests](https://user-images.githubusercontent.com/73541683/159743093-828a4d22-bf2f-4c02-b853-a975b6d79665.png)

![Code request](https://user-images.githubusercontent.com/73541683/159742859-287fa3a7-28fa-411a-9f7c-72fb697d1549.png)

I'm using Auth0 and the config is at it follows:
```
export const oidConfig: AuthProviderProps = {
  authority: '....',
  client_id: '...',
  userStore: new WebStorageStateStore({
        store: new InMemoryWebStorage()
      }),
  stateStore: new WebStorageStateStore({
    store: window.sessionStorage
  }),
  staleStateAgeInSeconds: 60,
  extraQueryParams: { audience: '...' },
  redirect_uri: '...'
}
```

I believe that is something related to the IFrame because if I try to force it when the token expiration event is sent, the frame would time out.

**Comment by pamapa** [comment]
Please have a look at the underlying library `oidc-client-ts`, renew is implemented there. Also notice that in v2.0.1 and v2.0.2 `oidc-client-ts` we fixed issues in that direction.

**Comment by mariusflorescu** [comment]
I've just upgraded the libraries to the latest versions, still happening.

I was previously on `2.0.1` for oidc-client-ts (I've introduced those packages last week)

**Comment by pamapa** [comment]
So this is not a regression and still happening.

Enable logging of the underlying library `oidc-client-ts` should help to see what the problem is:
```
import { Log } from "oidc-client-ts";
Log.setLogger(console);
Log.setLevel(Log.DEBUG);
```
And "Preserve Logs" in the browsers console, as the renew is done via iframe...

**Comment by pamapa** [comment]
The url used for the silent renew is taken from the settings property `silent_redirect_uri`. See [here](https://github.com/authts/oidc-client-ts/blob/c9fcaa0396148c2cae942b2e9a4ea1e6633a0bcc/src/UserManager.ts#L234). If `silent_redirect_uri` is not set it will use `redirect_uri` for it. See [here](https://github.com/authts/oidc-client-ts/blob/c9fcaa0396148c2cae942b2e9a4ea1e6633a0bcc/src/UserManagerSettings.ts#L115).

**Comment by mariusflorescu** [comment]
This is what I'm getting with the debug logger.

<img width="517" alt="Debug" src="https://user-images.githubusercontent.com/73541683/159758996-a7631b1f-135a-4b02-ad43-8f4cecf9a745.png">

Mhm, the thing with `silent_redirect_uri` confuses me a little bit not going to lie. It's not currently set, it uses the default `redirect_uri`. Like both the authorized redirects from `singinRedirect` and `singinSilent` work, however, the request that contains the code points to a different URL (`https` instead of `http`). Do you think it's due to the lack of `silent_redirect_uri` ?

**Comment by pamapa** [comment]
I think you are confused: In the above picture the `http://localhost:3000` is where our SAP application is running. This has nothing to do with the `silent_redirect_uri`. However what i see in that picture is that when doing the silent renew i somehow **timed out**. The question is why does the identity server not return an answer. If something is missing in the request i would expect to receive an error. Maybe you have configuration/permission problem.

e.g. set "Preserve Log" in the network browser DevTools to see the full network traffic.

**Comment by mariusflorescu** [comment]
I've read the auth0 silent renew process before opening the ticket.

The request is being made with correct parameters.

If it helps you:
The request for `singinRedirect` is sent with the following query params
```
https://mylink.com/authorize?client_id=myclientid&redirect_uri=http%3A%2F%2Flocalhost%3A3000&response_type=code&scope=myscope&state=mystate&code_challenge=mycodechanllange&code_challenge_method=S256&response_mode=query&audience=myaudience
```

And for the `signinSilent` the only difference is that I've got `prompt=none` additional as query param.

And the following requests with `code` and `state`:
- `http://localhost:3000/?code=code&state=state` (`signinRedirect`)
- `https://localhost:3000/?code=code&state=state` (`signinSilent`, which fails most likely because is being pointed to https)

Let me know if there is any additional information that may help both of use figure if there is something wrong on my side or there is a bug.

**Comment by pamapa** [comment]
ah `http` vs `https`, that is strange.

That redirect_uri is coming back via `signinRedirect` respectively `signinSilent`. You can see it in the request query params like you pasted for `signinRedirect` above. How does that request look like for `signinSilent`?

**Comment by mariusflorescu** [comment]
The only difference between those 2 requests is that `signinSilent` has an additional query param of `prompt=none`

**Comment by pamapa** [comment]
hmm if your configuration is correct, then your identity server changes `http` to `https`. This library and `oidc-client-ts` do definitely not change that url....

**Comment by mariusflorescu** [comment]
I'm using Auth0, with their library everything seems to be working perfectly and I haven't switched anything since then configuration wise.

**Comment by pamapa** [comment]
Can you double check the silent renew URL, between working and not working?
[Here](https://github.com/authts/oidc-client-ts/blob/64dba7c6dfc8ac88fe2424e11c8094c9e938cac8/src/SigninRequest.ts#L98) is the code where the redirect_url is added to the query.

**Comment by mariusflorescu** [comment]
the `redirect_url` for both `signinRedirect` and `singinSilent` is sent as a **query param** and is the *same*.  Pointing to **HTTP** localhost:3000

**Comment by pamapa** [comment]
@kherock any idea what could go wrong in that case?
